version: '3.9'
services:
  back:
    build: ./backend/
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - type: bind
        source: "./backend"
        target: "/backend"
  front:
    build: ./frontend/
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: "./frontend"
        target: "/frontend"
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
        - ${DB_PORT}:3306
    volumes:
        - db-store:/var/lib/mysql
        - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  db-store: